// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nww24hTmYBqrO3NsoAz2cW0iETEHOC4',
    appId: '1:609137126443:web:db3798351ae7acc7024e6e',
    messagingSenderId: '609137126443',
    projectId: 'techigh-todo-dev',
    authDomain: 'techigh-todo-dev.firebaseapp.com',
    storageBucket: 'techigh-todo-dev.appspot.com',
    measurementId: 'G-4PRYP2PRVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgkd4qH9UOhUcP2GFjyOnzaWc-p8Z_a4',
    appId: '1:609137126443:android:282b9e7f904c058e024e6e',
    messagingSenderId: '609137126443',
    projectId: 'techigh-todo-dev',
    storageBucket: 'techigh-todo-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegkbX2NUY9Vs6dlZzPF_kVfgdv-0VsvY',
    appId: '1:609137126443:ios:6ca7767ee3399fb3024e6e',
    messagingSenderId: '609137126443',
    projectId: 'techigh-todo-dev',
    storageBucket: 'techigh-todo-dev.appspot.com',
    iosClientId: '609137126443-i321t6gfskja8k6amiuh5m2qr00jl3ij.apps.googleusercontent.com',
    iosBundleId: 'com.techigh.devApp1',
  );
}
